Name:           ros-indigo-libsbp
Version:        1.1.1
Release:        4%{?dist}
Summary:        ROS libsbp package

Group:          Development/Libraries
License:        LGL3
Source0:        %{name}-%{version}.tar.gz

BuildRequires:  ros-indigo-catkin

%description
Switftnav libspb realeases into ROS ecosystem

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Wed Aug 10 2016 Michael Stoll <michael.stoll@stolltec.com> - 1.1.1-4
- Autogenerated by Bloom

* Wed Aug 10 2016 Michael Stoll <michael.stoll@stolltec.com> - 1.1.1-3
- Autogenerated by Bloom

* Tue Aug 09 2016 Michael Stoll <michael.stoll@stolltec.com> - 1.1.1-2
- Autogenerated by Bloom

* Wed Aug 03 2016 Michael Stoll <michael.stoll@stolltec.com> - 1.1.1-1
- Autogenerated by Bloom

* Wed Aug 03 2016 Michael Stoll <michael.stoll@stolltec.com> - 1.1.1-0
- Autogenerated by Bloom

